name: Publish

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+**"]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Publish Maven
      uses: burrunan/gradle-cache-action@v1
      env:
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      with:
        job-id: jdk8-build-test
        arguments: >-
          build
          publishRelease
          -x test
        properties: |
          releaseVersion=${{ steps.tagName.outputs.tag }}
          ossrhUsername=${{ secrets.OSSRH_USER }}
          ossrhPassword=${{ secrets.OSSRH_PASS }}
          github.token=${{ secrets.GITHUB_TOKEN }}

    - name: Build Docs
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: dokkaHtml

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        clean: false
        folder: build/javadoc
